export enum FileResourceDomain {
  DATA_VALUE = 'DATA_VALUE',

  PUSH_ANALYSIS = 'PUSH_ANALYSIS',

  DOCUMENT = 'DOCUMENT',

  MESSAGE_ATTACHMENT = 'MESSAGE_ATTACHMENT',

  USER_AVATAR = 'USER_AVATAR',

  ORG_UNIT = 'ORG_UNIT',
}
